---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-manage-sap-v1-order
  failurePolicy: Fail
  name: vorder-v1.kb.io
  rules:
  - apiGroups:
    - manage.sap
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - orders
  sideEffects: None
