# This rule is not used by the project ordermanager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the manage.sap.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ordermanager
    app.kubernetes.io/managed-by: kustomize
  name: order-editor-role
rules:
- apiGroups:
  - manage.sap
  resources:
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manage.sap
  resources:
  - orders/status
  verbs:
  - get
