---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - manage.sap
  resources:
  - orders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manage.sap
  resources:
  - orders/finalizers
  verbs:
  - update
- apiGroups:
  - manage.sap
  resources:
  - orders/status
  verbs:
  - get
  - patch
  - update
