---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-manager-role
rules:
- apiGroups: 
  - "apps"
  resources: 
  - "deployments"
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: 
  - ""
  resources: 
  - "configmaps"
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups: 
  - "events.k8s.io"
  resources: 
  - "events"
  verbs: 
  - create
  - delete
  - get
  - list
  - patch
  - update
